import type { Config } from "tailwindcss";

const config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  safelist: [
    "text-[#000000]",
    "text-[#0000FF]",
    "text-[#00AA00]",
    "text-[#00AAAA]",
    "text-[#AA0000]",
    "text-[#AA00AA]",
    "text-[#AA5500]",
    "text-[#AAAAAA]",
    "text-[#555555]",
    "text-[#5555FF]",
    "text-[#33FF33]",
    "text-[#55FFFF]",
    "text-[#FF5555]",
    "text-[#FF55FF]",
    "text-[#FFEE00]",
    "text-[#FFFFFF]",
    "text-[#8968CD]",
    "hover:text-[#000000]",
    "hover:text-[#0000FF]",
    "hover:text-[#00AA00]",
    "hover:text-[#00AAAA]",
    "hover:text-[#AA0000]",
    "hover:text-[#AA00AA]",
    "hover:text-[#AA5500]",
    "hover:text-[#AAAAAA]",
    "hover:text-[#555555]",
    "hover:text-[#5555FF]",
    "hover:text-[#33FF33]",
    "hover:text-[#55FFFF]",
    "hover:text-[#FF5555]",
    "hover:text-[#FF55FF]",
    "hover:text-[#FFEE00]",
    "hover:text-[#FFFFFF]",
    "hover:text-[#8968CD]",

    "group-hover:text-[#33FF33]",
    "group-hover:text-[#FF5555]",
    "group-hover:text-[#FFEE00]",
    "group-hover:text-[#55FFFF]",
    "group-hover:text-[#5555FF]",
    "group-hover:text-[#FF55FF]",
    "group-hover:underline",
    "group",

    "h-[140px]",
    "w-60",
    "h-12",
    "flex",
    "gap-6",
    "gap-x-2",
    "shrink-0",
    "rounded-3xl",
    "border-muted",
    "text-base",
    "border-t-2",

    "from-[#00000050]",
    "from-[#0000FF50]",
    "from-[#00AA0050]",
    "from-[#00AAAA50]",
    "from-[#AA000050]",
    "from-[#AA00AA50]",
    "from-[#AA550050]",
    "from-[#AAAAAA50]",
    "from-[#55555550]",
    "from-[#5555FF50]",
    "from-[#33FF3350]",
    "from-[#55FFFF50]",
    "from-[#FF555550]",
    "from-[#FF55FF50]",
    "from-[#FFEE0050]",
    "from-[#FFFFFF50]",
    "from-[#8968CD50]",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;

export default config;
